"""Remove old columns

Revision ID: 5133a8a66862
Revises: 5ed2adcd3303
Create Date: 2026-05-11 18:17:47.332282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5133a8a66862'
down_revision: Union[str, Sequence[str], None] = '5ed2adcd3303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'years_experience')
    op.drop_column('applicants', 'research_outputs')
    op.drop_column('applicants', 'certifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('certifications', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('research_outputs', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('applicants', sa.Column('years_experience', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
