"""Add dynamic_data, is_internal, required_specialization

Revision ID: 5ed2adcd3303
Revises: 87e2fd82ff4a
Create Date: 2026-05-11 18:15:36.308102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ed2adcd3303'
down_revision: Union[str, Sequence[str], None] = '87e2fd82ff4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('dynamic_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.add_column('applicants', sa.Column('is_internal', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('positions', sa.Column('required_specialization', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'required_specialization')
    op.drop_column('applicants', 'is_internal')
    op.drop_column('applicants', 'dynamic_data')
    # ### end Alembic commands ###
