"""fix datetime columns

Revision ID: 87e2fd82ff4a
Revises: b084a334398a
Create Date: 2026-04-24 20:14:14.461605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e2fd82ff4a'
down_revision: Union[str, Sequence[str], None] = 'b084a334398a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allocations', 'allocated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using='allocated_at::timestamp without time zone')
    op.alter_column('applicants', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using='created_at::timestamp without time zone')
    op.alter_column('applicants', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using='updated_at::timestamp without time zone')
    op.alter_column('criteria', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using='created_at::timestamp without time zone')
    op.alter_column('criteria', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using='updated_at::timestamp without time zone')
    op.alter_column('departments', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using='created_at::timestamp without time zone')
    op.alter_column('positions', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using='created_at::timestamp without time zone')
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using='created_at::timestamp without time zone')
    op.alter_column('users', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using='updated_at::timestamp without time zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('positions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('criteria', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('criteria', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applicants', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applicants', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('allocations', 'allocated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
